# -*- coding: utf-8 -*-
print('type(123):',type(123))
print('type(123.1):',type(123.1))
print('type(\'123\'):',type('123'))
print('type(123)==type(456):', type(123)==type(456))
print('type(123)==int:', type(123)==int)
print('type(abs):',type(abs))
print('type(lambda x: x):',type(lambda x: x))
print('type((x for x in range(10))):',type((x for x in range(10))))
print('可以判断一个变量是否是某些类型中的一种 isinstance([1, 2, 3], (list, tuple)):', isinstance([1, 2, 3], (list, tuple)))
print('如果要获得一个对象的所有属性和方法，可以使用dir()函数')
print('dir(\'ABC\'):',dir('ABC'))
print('len(\'ABC\'):',len('ABC'))
print('\'ABC\'.__len__():','ABC'.__len__())